# Generated by Django 2.2 on 2019-04-26 07:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_movie_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='length',
            field=models.IntegerField(default=0, help_text='Enter Length in Minutes.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Length'),
        ),
    ]
