# Generated by Django 2.2 on 2019-04-26 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='length',
        ),
    ]
